#ifndef GPIO_H
# define GPIO_H

#  include <stdint.h>

#  define GPIO23_STATUS								0x0b8u
#  define GPIO23_CONTROL							0x0bcu

#  define GPIO_STATUS_OUTFROMPERI					(0x1u << 8u)
#  define GPIO_STATUS_OUTTOPAD						(0x1u << 9u)
#  define GPIO_STATUS_OEFROMPERI					(0x1u << 12u)
#  define GPIO_STATUS_OETOPAD						(0x1u << 13u)
#  define GPIO_STATUS_INISDIRECT					(0x1u << 16u)
#  define GPIO_STATUS_INFROMPAD						(0x1u << 17u)
#  define GPIO_STATUS_INFILTERED					(0x1u << 18u)
#  define GPIO_STATUS_INTOPERI						(0x1u << 19u)
#  define GPIO_STATUS_EVENT_EDGE_LOW				(0x1u << 20u)
#  define GPIO_STATUS_EVENT_EDGE_HIGH				(0x1u << 21u)
#  define GPIO_STATUS_EVENT_LEVEL_LOW				(0x1u << 22u)
#  define GPIO_STATUS_EVENT_LEVEL_HIGH				(0x1u << 23u)
#  define GPIO_STATUS_EVENT_F_EDGE_LOW				(0x1u << 24u)
#  define GPIO_STATUS_EVENT_F_EDGE_HIGH				(0x1u << 25u)
#  define GPIO_STATUS_EVENT_DB_LEVEL_LOW			(0x1u << 26u)
#  define GPIO_STATUS_EVENT_DB_LEVEL_HIGH			(0x1u << 27u)
#  define GPIO_STATUS_IRQCOMBINED					(0x1u << 28u)
#  define GPIO_STATUS_IRQTOPROC						(0x1u << 29u)

#  define GPIO_CONTROL_FUNCSEL_OFFSET				0u
#  define GPIO_CONTROL_FUNCSEL_MASK					0x0000001Fu

#  define GPIO_CONTROL_F_M_OFFSET					5u
#  define GPIO_CONTROL_F_M_MASK						0x000007E0u

#  define GPIO_CONTROL_OUTOVER_OFFSET				12u
#  define GPIO_CONTROL_OUTOVER_MASK					0x00003000u

#  define GPIO_CONTROL_OEOVER_OFFSET				14u
#  define GPIO_CONTROL_OEOVER_MASK					0x0000C000u

#  define GPIO_CONTROL_INOVER_OFFSET				16u
#  define GPIO_CONTROL_INOVER_MASK					0x00030000u

#  define GPIO_CONTROL_IRQMASK_EDGE_LOW_OFFSET		20u
#  define GPIO_CONTROL_IRQMASK_EDGE_LOW_MASK		0x00100000u

#  define GPIO_CONTROL_IRQMASK_EDGE_HIGH_OFFSET		21u
#  define GPIO_CONTROL_IRQMASK_EDGE_HIGH_MASK		0x00200000u

#  define GPIO_CONTROL_IRQMASK_LEVEL_LOW_OFFSET		22u
#  define GPIO_CONTROL_IRQMASK_LEVEL_LOW_MASK		0x00400000u

#  define GPIO_CONTROL_IRQMASK_LEVEL_HIGH_OFFSET	23u
#  define GPIO_CONTROL_IRQMASK_LEVEL_HIGH_MASK		0x00800000u

#  define GPIO_CONTROL_IRQMASK_F_EDGE_LOW_OFFSET	24u
#  define GPIO_CONTROL_IRQMASK_F_EDGE_LOW_MASK		0x01000000u

#  define GPIO_CONTROL_IRQMASK_F_EDGE_HIGH_OFFSET	25u
#  define GPIO_CONTROL_IRQMASK_F_EDGE_HIGH_MASK		0x02000000u

#  define GPIO_CONTROL_IRQMASK_DB_LEVEL_LOW_OFFSET	26u
#  define GPIO_CONTROL_IRQMASK_DB_LEVEL_LOW_MASK	0x04000000u

#  define GPIO_CONTROL_IRQMASK_DB_LEVEL_HIGH_OFFSET	27u
#  define GPIO_CONTROL_IRQMASK_DB_LEVEL_HIGH_MASK	0x08000000u

#  define GPIO_CONTROL_IRQRESET_OFFSET				28u
#  define GPIO_CONTROL_IRQRESET_MASK				0x10000000u

#  define GPIO_CONTROL_IRQOVER_OFFSET				30u
#  define GPIO_CONTROL_IRQOVER_MASK					0xC0000000u

#endif
